spring.datasource.url=jdbc:postgresql://localhost:5432/uppskriftabok
spring.datasource.username=uppskriftabok
spring.datasource.password=uppskriftabok
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
